name: Test go-workers2
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6.0-alpine
        ports:
          - 6379:6379

    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: make test
